### ISSUE TITLE
Can't run test cases

### ISSUE THREAD

**Issue by wcmille** [TriggerAu/TransferWindowPlanner#36]
Trying to run the test cases. Get this error message:

![image](https://cloud.githubusercontent.com/assets/14813745/10063293/b042ba6e-6231-11e5-8b01-516b7aaa973f.png)

**Comment by wcmille** [comment]
Here's the offending line:
            HoursPerDay = GameSettings.KERBIN_TIME ? 6 : 24;

GameSettings seems to be from a KSP assembly. Could it be because the test runner is not initializing this?

**Comment by TriggerAu** [comment]
Sorry to take soo long on this one, just onto it now.

Unfortunately it looks like Unity have changed the way they have defined the methods underpinning this so the code that uses the KSP dlls no longer works in newer version of Unity - still works in the 0.90 games version, but not later. Will look at adjusting the code to use constants for now and see if its an easy win

**Comment by TriggerAu** [comment]
Gonna close this one off here - I can't fix it in the short term unfortunately will have to be a known issue
