### ISSUE TITLE
KAC: Margin applied "backwards"

### ISSUE THREAD

**Issue by lwho** [TriggerAu/TransferWindowPlanner#38]
When creating a Kerbal Alarm Clock alarm from the transfer window planner, the configured margin is applied in the wrong direction.

I.e. if the calculated departure is in 150 days and I configure a margin of 10 days (60 hours), the time to alarm will always be 150 days (i.e. directly at the departure time, no matter how the margin was configured) and the time to event is reported as 160 days (departure plus margin, i.e. 10 days too late).

Time to alarm should be 140 days (departure minus margin) and time to event 150 days instead.

Edit: Transfer Window Planner v1.3.1.0 and Kerbal Alarm Clock v3.4.0.0 installed via CKAN on KSP 1.0.5 Linux amd64

**Comment by TriggerAu** [comment]
Found it and fixing now
