### ISSUE TITLE
Feature request: move the settings.cfg to a PluginData folder

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [TriggerAu/TransferWindowPlanner#46]
It's been brought up and resolved in at least one of your other mods (e.g. [Kerbal Alarm Clock](https://github.com/TriggerAu/KerbalAlarmClock/issues/166)), but I want to bring this one to your attention, since TWP stores the date when it checks a version, which changes once a day and forces Module Manager to reload the entire patching process during game start.

**Comment by enceos** [comment]
@TriggerAu  This particular line makes the ModuleManager trigger the cache rebuilding:
	VersionCheckDate_AttemptStored = ####-##-##
	VersionCheckDate_SuccessStored = ####-##-##

Since it's a volatile data, looks like TWP also needs a PluginData folder.

**Comment by TriggerAu** [comment]
This one is done as above
