### ISSUE TITLE
Gray Screen and NaN plots from Laythe to Vall

### ISSUE THREAD

**Issue by gordonfpanam** [TriggerAu/TransferWindowPlanner#53]
![screenshot2](https://user-images.githubusercontent.com/25485283/36291955-176b3fc6-1294-11e8-9d66-19473c0f3564.png)

Folks noticed this when using Alien Space Programs to relocate the KSC to Laythe, but this happens on an otherwise stock game as well, with only Transfer Window Planner installed.

Plots from Laythe to other Jool moons look correct, and plotting from Vall back to Laythe looks correct too.

[After checking Alexmoon's tool] The original tool puts this large gray area in the middle of the plot, with the optimal areas just to the edge of that gray area. Maybe the original code has this problem too.

![alexmoongrayarea](https://user-images.githubusercontent.com/25485283/36292162-42980b92-1295-11e8-865c-89d7a7ef3016.png)

**Comment by TriggerAu** [comment]
Found it, issue with the impossible transfer an dthe rendrering of NaN in the UI code
